export const recipes = [
  {
    slug: "samosa-pinwheels",
    title: "Samosa Pinwheels",
    category: "Snacks",
    tags: ["Indian-inspired", "Snacks"],
    cookTime: "30 min",
    description: "Flaky, crispy pinwheels stuffed with spiced potato filling — all the samosa flavor without the fuss.",
    image: "/pinwheels.jpg",
    ingredients: [
      "1 sheet puff pastry",
      "2 medium potatoes, boiled and mashed",
      "1/2 cup peas",
      "1/2 white onion diced",
      "1 tsp minced ginger and garlic",
      "2 tbsp oil",
      "1 tsp cumin",
      "2 tsp garam masala",
      "1/2 tsp turmeric",
      "1/2 tsp chili powder",
      "1/2 tsp cinnamon powder",
      "1/2 tsp cumin powder",
      "salt to taste",
    ],
    instructions: [
      "Preheat oven to 350°F.",
      "Chop onions, ginger, and garlic",
      "boil potatoes",
      "In a separate pan, heat oil and add cumin seeds and ginger/garlic mix.",
      "Once fragrant, add onions and cook until translucent",
      "Then add peas and all the spices.",
      "Finally mash potatoes into the mixture.",
      "On a baking tray, add parchment paper and then roll out puff pastry onto the sheet and spread filling evenly.",
      "Roll into a log and slice into 1-inch pieces.",
      "Place pieces onto the baking tray and Bake for 20-25 minutes until golden brown.",
    ],
  },
  {
    slug: "cinnamon-rolls",
    title: "Cinnamon Rolls",
    category: "Baking",
    tags: ["Baking", "Sweet"],
    cookTime: "2 hr",
    description: "Soft, gooey cinnamon rolls with a cream cheese glaze. Worth every minute. Can be made yeastless and eggless!",
    image: "/cinnamonroll.jpg",
    ingredients: [
      "3 cups flour",
      "1 packet instant yeast or 1:1 tsp baking soda and vinegar",
      "1/2 cup warm milk",
      "1/4 cup sugar",
      "1/4 cup butter, melted",
      "1 egg or 1/4 greek yogurt",
      "1/2 tsp salt",
      "1/2 cup brown sugar",
      "2 tsp cinnamon",
      "4 oz cream cheese",
      "1 cup powdered sugar",
    ],
    instructions: [
      "Mix yeast with warm milk and let sit 5 minutes or combine baking soda and lemon juice in a bowl.",
      "Combine flour, sugar, salt, butter, egg/yogurt, and yeast/baking soda mixture. Knead until smooth.",
      "Let dough rise for 1 hour.",
      "Roll out dough, spread with butter, brown sugar, and cinnamon.",
      "Roll into a log, slice, and place in a baking dish.",
      "Let rise 30 more minutes, then bake at 350°F for 25 minutes.",
      "Mix cream cheese and powdered sugar for glaze and drizzle on top.",
    ],
  },
  {
    slug: "chickpea-salad",
    title: "Chickpea Salad",
    category: "Salads",
    tags: ["Salad", "Fresh"],
    cookTime: "15 min",
    description: "A bright, herby chickpea salad that comes together in minutes and tastes even better the next day.",
    image: "/ChickpeaSalad.jpg",
    ingredients: [
      "1 can chickpeas, drained",
      "1 cucumber, diced",
      "1 cup cherry tomatoes, halved",
      "1/4 red onion, finely chopped",
      "1/4 cup fresh cilantro",
      "1 bell pepper diced",
      "1/4 cup finely chopped mint",
      "1 pomogranate peeled",
      "2 tbsp olive oil",
      "1 lemon, juiced",
      "2 tbsp chaat masala",
      "1 tsp chilli powder",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Drain and rinse chickpeas.",
      "Chop all produce and add to a large bowl.",
      "Toss with olive oil, lemon juice, and seasoning.",
      "Top with fresh cilantro and mint.",
    ],
  },
  {
    slug: "mediterranean-inspired-salad",
    title: "Mediterranean Inspired Salad",
    category: "Salads",
    tags: ["Salad", "Fresh"],
    cookTime: "15 min",
    description: "The salad that convinces you that fruits belong in salads.",
    image: "/med_chickpea_salad.JPG",
    ingredients: [ 
      "1/2 cucumber chopped",
      "1 tomato diced ",
      " handful of arugula (arugula tastes better but if you plan to store it, use kale or chickpeas because arugula tends to get soggy in the fridge)",
      "1/4 red onion, finely chopped",
      "1/4 cup fresh cilantro",
      "1 bell pepper diced",
      " 2 blood oranges peeled and chopped",
      "1 pomogranate peeled",
      "2 tbsp olive oil",
      "2-3 tbsp balsamic glaze",
      "1/4 cup crumbled feta",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Drain and rinse chickpeas/leafy greens.",
      "Chop all produce and add to a large bowl.",
      "Toss with olive oil, balsamic glaze, feta, and seasoning.",
      "Top with fresh cilantro.",
    ],
  }
];